KapuzenMC/webseite/blog/urls.py
from django.urls import path
from . import views

app_name = 'Blog'
urlpatterns = [
    path('', views.index, name='index'),
]

KapuzenMC/webseite/web/urls.py
from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('Member/', views.member_view, name='member'),
]

KapuzenMC/webseite/webseite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', include('web.urls')),
]

KapuzenMC/webseite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.CharField(max_length=250)
    created_at = models.DateTimeField(default=timezone.now)

KapuzenMC/webseite/web/models.py
from django.db import models

# Create your models here.

KapuzenMC/webseite/web/forms.py
from django import forms
from django.contrib.auth.models import User


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=35, label='Username Eintragen')
    password = forms.CharField(min_length=6, max_length=50,label='Passwort Eintargen', widget=forms.PasswordInput)
    email = forms.EmailField(label='Email Eintragen')

    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError('Diesen Usernamen gibt es schon!')
        return username

    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError('Diese Email gibt es schon!')
        return email

class LoginForm(forms.Form):
    username = forms.CharField(max_length=35, label='Username Eintragen')
    password = forms.CharField(min_length=6, max_length=50, label='Passwort Eintargen', widget=forms.PasswordInput)

KapuzenMC/webseite/blog/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'blog/base.html')

KapuzenMC/webseite/web/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import RegisterForm, LoginForm


def index(request):
    return render(request, 'web/base.html')


def register_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('web:member'))
    register_form = RegisterForm()
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        if register_form.is_valid():

            username = register_form.cleaned_data['username']
            password = register_form.cleaned_data['password']
            email = register_form.cleaned_data['Email']
            User.objects.create_user(username=username, password=password, email=email)
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('web:member'))

    return render(request, 'web/register.html', {'register_form': register_form})


def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse('web:member'))
    login_form = LoginForm()
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect(reverse('web:member'))

    return render(request, 'web/login.html', {'login_form': login_form})


@login_required
def member_view(request):
    return render(request, 'web/member.html')


def logout_view(request):
    logout(request)
    return redirect(reverse('web:index'))

KapuzenMC/webseite/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>mein blog</h1>
</body>
</html>

KapuzenMC/webseite/web/templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} BlockPost {% endblock %}</title>
</head>
<body>
<h1>Blog-Post</h1>
{% if request.user.is_authenticated %}
<p>Hallo {{request.user.username}}!</p>
<a href="{% url 'web:logout' %}">Logout</a>
{% else %}
<a href="{% url 'web:login' %}">Login</a>
<a href="{% url 'web:register' %}">register</a>
{% endif %}
{% block authForm %}


{% endblock %}
</body>
<style>
    .Buttons{
        background-color: #262626;
    }
</style>
</html>

KapuzenMC/webseite/web/templates/web/login.html
{% extends 'web/base.html' %}

{% block title %} BlockPost - Login {% endblock %}

{% block authForm %}

<form method="post" action="">
     {% csrf_token %}
     {{ login_form.as_p }}
    <button type="submit">Login</button>


</form>

{% endblock %}

KapuzenMC/webseite/web/templates/web/register.html
{% extends 'web/base.html' %}

{% block title %} BlockPost - Register {% endblock %}

{% block authForm %}

<form method="post" action="">
    {% csrf_token %}
    {{ register_form.as_p }}

    <button type="submit">Register</button>


</form>

{% endblock %}